### ISSUE TITLE
Generating data for website

### ISSUE THREAD

**Issue by itsfolf** [KiranGershenfeld/VisualizingTwitchCommunities#10]
How is the data.json file for sigma visualization generated?

**Comment by YoannDeb** [comment]
You have to add export command when lauching main.py
i.e. : ```python main.py export```
I looked after that for a little while, should be in the doc I think...

**Comment by itsfolf** [comment]
> You have to add export command when lauching main.py i.e. : `python main.py export` I looked after that for a little while, should be in the doc I think...

Can't find any mentions to export in the whole project and the only main.py in DataCollection doesn't have anything related to that

**Comment by KiranGershenfeld** [comment]
The data.json file in the Website directory was generated in Gephi and exported via a plugin to the SimgaJS template. The data that I put into Gephi is located in the Visualization/GephiData directory. They are named by date so look for the ones that  start with 10.05. The actual .gephi graph file was not uploaded because data.json is all that is needed to create the web implementation. 

Hopefully that helps :)

**Comment by YoannDeb** [comment]
> 
> 
> > You have to add export command when lauching main.py i.e. : `python main.py export` I looked after that for a little while, should be in the doc I think...
> 
> Can't find any mentions to export in the whole project and the only main.py in DataCollection doesn't have anything related to that

Sorry I confused with a fork (https://github.com/necauqua/VisualizingTwitchCommunities)...
